
// Generated by Cadence Genus(TM) Synthesis Solution 19.12-s121_1
// Generated on: Nov 11 2021 11:12:24 IST (Nov 11 2021 05:42:24 UTC)

// Verification Directory fv/thirty_two_bit_adder 

module base_logic(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_1(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_2(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_3(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_4(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_5(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_6(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_7(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_8(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_9(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_10(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_11(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_12(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_13(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_14(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_15(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_16(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_17(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_18(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_19(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_20(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_21(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_22(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_23(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_24(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_25(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_26(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_27(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_28(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_29(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_30(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_31(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module black_cell(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_1(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_2(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_3(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_4(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_5(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_6(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_7(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_8(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_9(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_10(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_11(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_12(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_13(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_14(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_15(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_16(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_17(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_18(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_19(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_20(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_21(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_22(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_23(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_24(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_25(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_26(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_27(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_28(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_29(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_30(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_31(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_32(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_33(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_34(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_35(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_36(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_37(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_38(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_39(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_40(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_41(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g16(.A1 (Pk_1j), .A2 (Gk_1j), .B (Gik), .Z (Gij));
endmodule

module black_cell_42(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_43(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_44(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_45(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_46(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_47(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_48(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module FA(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_1(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_2(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_3(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_4(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_5(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_6(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_7(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_8(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_9(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_10(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_11(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_12(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_13(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_14(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_15(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_16(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_17(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_18(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_19(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_20(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_21(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_22(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_23(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_24(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_25(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_26(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_27(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_28(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_29(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_30(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_31(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module grey_cell(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
endmodule

module grey_cell_1(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_2(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_3(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_4(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
endmodule

module grey_cell_5(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_6(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_7(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_8(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
endmodule

module grey_cell_9(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_10(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
endmodule

module grey_cell_11(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_12(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_13(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_14(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_15(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_16(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
endmodule

module grey_cell_17(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_18(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
endmodule

module grey_cell_19(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_20(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
endmodule

module grey_cell_21(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_22(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
endmodule

module grey_cell_23(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_24(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_25(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_26(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_27(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_28(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_29(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_30(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_31(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AN2M2R g9(.A (Gk_1j), .B (Pik), .Z (Gij));
endmodule

module thirty_two_bit_adder(S, Cout, a, b, c, Cin);
  input [31:0] a, b, c;
  input Cin;
  output [32:0] S;
  output Cout;
  wire [31:0] a, b, c;
  wire Cin;
  wire [32:0] S;
  wire Cout;
  wire [31:0] S_x;
  wire [32:0] G;
  wire [31:0] cy;
  wire [32:0] P;
  wire [32:0] Gw1;
  wire [32:0] Pw1;
  wire [32:0] Gw2;
  wire [32:0] Pw2;
  wire [32:0] Gw3;
  wire [32:0] Pw3;
  wire [32:0] Gw4;
  wire [32:0] Pw4;
  wire [32:0] Gn;
  wire [32:0] Gw5;
  wire UNCONNECTED, UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0;
  base_logic B0(S_x[0], Cin, S[0], G[0]);
  base_logic_1 B1(S_x[1], cy[0], P[1], G[1]);
  base_logic_2 B2(S_x[2], cy[1], P[2], G[2]);
  base_logic_3 B3(S_x[3], cy[2], P[3], G[3]);
  base_logic_4 B4(S_x[4], cy[3], P[4], G[4]);
  base_logic_5 B5(S_x[5], cy[4], P[5], G[5]);
  base_logic_6 B6(S_x[6], cy[5], P[6], G[6]);
  base_logic_7 B7(S_x[7], cy[6], P[7], G[7]);
  base_logic_8 B8(S_x[8], cy[7], P[8], G[8]);
  base_logic_9 B9(S_x[9], cy[8], P[9], G[9]);
  base_logic_10 B10(S_x[10], cy[9], P[10], G[10]);
  base_logic_11 B11(S_x[11], cy[10], P[11], G[11]);
  base_logic_12 B12(S_x[12], cy[11], P[12], G[12]);
  base_logic_13 B13(S_x[13], cy[12], P[13], G[13]);
  base_logic_14 B14(S_x[14], cy[13], P[14], G[14]);
  base_logic_15 B15(S_x[15], cy[14], P[15], G[15]);
  base_logic_16 B16(S_x[16], cy[15], P[16], G[16]);
  base_logic_17 B17(S_x[17], cy[16], P[17], G[17]);
  base_logic_18 B18(S_x[18], cy[17], P[18], G[18]);
  base_logic_19 B19(S_x[19], cy[18], P[19], G[19]);
  base_logic_20 B20(S_x[20], cy[19], P[20], G[20]);
  base_logic_21 B21(S_x[21], cy[20], P[21], G[21]);
  base_logic_22 B22(S_x[22], cy[21], P[22], G[22]);
  base_logic_23 B23(S_x[23], cy[22], P[23], G[23]);
  base_logic_24 B24(S_x[24], cy[23], P[24], G[24]);
  base_logic_25 B25(S_x[25], cy[24], P[25], G[25]);
  base_logic_26 B26(S_x[26], cy[25], P[26], G[26]);
  base_logic_27 B27(S_x[27], cy[26], P[27], G[27]);
  base_logic_28 B28(S_x[28], cy[27], P[28], G[28]);
  base_logic_29 B29(S_x[29], cy[28], P[29], G[29]);
  base_logic_30 B30(S_x[30], cy[29], P[30], G[30]);
  base_logic_31 B31(S_x[31], cy[30], P[31], G[31]);
  black_cell BL3(G[3], P[3], G[2], P[2], Gw1[3], Pw1[3]);
  black_cell_1 BL51(G[5], P[5], G[4], P[4], Gw1[5], Pw1[5]);
  black_cell_2 BL52(Gw1[5], Pw1[5], Gw1[3], Pw1[3], Gw2[5], Pw2[5]);
  black_cell_3 BL71(G[7], P[7], G[6], P[6], Gw1[7], Pw1[7]);
  black_cell_4 BL72(Gw1[7], Pw1[7], Gw1[5], Pw1[5], Gw2[7], Pw2[7]);
  black_cell_5 BL91(G[9], P[9], G[8], P[8], Gw1[9], Pw1[9]);
  black_cell_6 BL92(Gw1[9], Pw1[9], Gw1[7], Pw1[7], Gw2[9], Pw2[9]);
  black_cell_7 BL93(Gw2[9], Pw2[9], Gw2[5], Pw2[5], Gw3[9], Pw3[9]);
  black_cell_8 BL111(G[11], P[11], G[10], P[10], Gw1[11], Pw1[11]);
  black_cell_9 BL112(Gw1[11], Pw1[11], Gw1[9], Pw1[9], Gw2[11],
       Pw2[11]);
  black_cell_10 BL113(Gw2[11], Pw2[11], Gw2[7], Pw2[7], Gw3[11],
       Pw3[11]);
  black_cell_11 BL131(G[13], P[13], G[12], P[12], Gw1[13], Pw1[13]);
  black_cell_12 BL132(Gw1[13], Pw1[13], Gw1[11], Pw1[11], Gw2[13],
       Pw2[13]);
  black_cell_13 BL133(Gw2[13], Pw2[13], Gw2[9], Pw2[9], Gw3[13],
       Pw3[13]);
  black_cell_14 BL151(G[15], P[15], G[14], P[14], Gw1[15], Pw1[15]);
  black_cell_15 BL152(Gw1[15], Pw1[15], Gw1[13], Pw1[13], Gw2[15],
       Pw2[15]);
  black_cell_16 BL153(Gw2[15], Pw2[15], Gw2[11], Pw2[11], Gw3[15],
       Pw3[15]);
  black_cell_17 BL171(G[17], P[17], G[16], P[16], Gw1[17], Pw1[17]);
  black_cell_18 BL172(Gw1[17], Pw1[17], Gw1[15], Pw1[15], Gw2[17],
       Pw2[17]);
  black_cell_19 BL173(Gw2[17], Pw2[17], Gw2[13], Pw1[13], Gw3[17],
       Pw3[17]);
  black_cell_20 BL174(Gw3[17], Pw3[17], Gw3[9], Pw3[9], Gw4[17],
       Pw4[17]);
  black_cell_21 BL191(G[19], P[19], G[18], P[18], Gw1[19], Pw1[19]);
  black_cell_22 BL192(Gw1[19], Pw1[19], Gw1[17], Pw1[17], Gw2[19],
       Pw2[19]);
  black_cell_23 BL193(Gw2[19], Pw2[19], Gw2[15], Pw1[19], Gw3[19],
       Pw3[19]);
  black_cell_24 BL194(Gw3[19], Pw3[19], Gw3[11], Pw3[11], Gw4[19],
       Pw4[19]);
  black_cell_25 BL211(G[21], P[21], G[20], P[20], Gw1[21], Pw1[21]);
  black_cell_26 BL212(Gw1[21], Pw1[21], Gw1[19], Pw1[19], Gw2[21],
       Pw2[21]);
  black_cell_27 BL213(Gw2[21], Pw2[21], Gw2[17], Pw1[17], Gw3[21],
       Pw3[21]);
  black_cell_28 BL214(Gw3[21], Pw3[21], Gw3[13], Pw3[13], Gw4[21],
       Pw4[21]);
  black_cell_29 BL231(G[23], P[23], G[22], P[22], Gw1[23], Pw1[23]);
  black_cell_30 BL232(Gw1[23], Pw1[23], Gw1[21], Pw1[21], Gw2[23],
       Pw2[23]);
  black_cell_31 BL233(Gw2[23], Pw2[23], Gw2[19], Pw1[19], Gw3[23],
       Pw3[23]);
  black_cell_32 BL234(Gw3[23], Pw3[23], Gw3[15], Pw3[15], Gw4[23],
       Pw4[23]);
  black_cell_33 BL251(G[25], P[25], G[24], P[24], Gw1[25], Pw1[25]);
  black_cell_34 BL252(Gw1[25], Pw1[25], Gw1[23], Pw1[23], Gw2[25],
       Pw2[25]);
  black_cell_35 BL253(Gw2[25], Pw2[25], Gw2[21], Pw1[21], Gw3[25],
       Pw3[25]);
  black_cell_36 BL254(Gw3[25], Pw3[25], Gw3[17], Pw3[17], Gw4[25],
       Pw4[25]);
  black_cell_37 BL271(G[27], P[27], G[26], P[26], Gw1[27], Pw1[27]);
  black_cell_38 BL272(Gw1[27], Pw1[27], Gw1[25], Pw1[25], Gw2[27],
       Pw2[27]);
  black_cell_39 BL273(Gw2[27], Pw2[27], Gw2[23], Pw1[23], Gw3[27],
       Pw3[27]);
  black_cell_40 BL274(Gw3[27], Pw3[27], Gw3[19], Pw3[19], Gw4[27],
       Pw4[27]);
  black_cell_41 BL291(G[29], UNCONNECTED_HIER_Z, G[28], P[29], Gw1[29],
       UNCONNECTED);
  black_cell_42 BL292(Gw1[29], P[29], Gw1[27], Pw1[27], Gw2[29],
       Pw2[29]);
  black_cell_43 BL293(Gw2[29], Pw2[29], Gw2[25], Pw1[25], Gw3[29],
       Pw3[29]);
  black_cell_44 BL294(Gw3[29], Pw3[29], Gw3[21], Pw3[21], Gw4[29],
       Pw4[29]);
  black_cell_45 BL311(G[31], P[31], G[30], P[30], Gw1[31], Pw1[31]);
  black_cell_46 BL312(Gw1[31], Pw1[31], Gw1[27], Pw1[27], Gw2[31],
       Pw2[31]);
  black_cell_47 BL313(Gw2[31], Pw2[31], Gw2[25], Pw1[25], Gw3[31],
       Pw3[31]);
  black_cell_48 BL314(Gw3[31], Pw3[31], Gw3[21], Pw3[21], Gw4[31],
       Pw4[31]);
  FA F0(a[0], b[0], c[0], cy[0], S_x[0]);
  FA_1 F1(a[1], b[1], c[1], cy[1], S_x[1]);
  FA_2 F2(a[2], b[2], c[2], cy[2], S_x[2]);
  FA_3 F3(a[3], b[3], c[3], cy[3], S_x[3]);
  FA_4 F4(a[4], b[4], c[4], cy[4], S_x[4]);
  FA_5 F5(a[5], b[5], c[5], cy[5], S_x[5]);
  FA_6 F6(a[6], b[6], c[6], cy[6], S_x[6]);
  FA_7 F7(a[7], b[7], c[7], cy[7], S_x[7]);
  FA_8 F8(a[8], b[8], c[8], cy[8], S_x[8]);
  FA_9 F9(a[9], b[9], c[9], cy[9], S_x[9]);
  FA_10 F10(a[10], b[10], c[10], cy[10], S_x[10]);
  FA_11 F11(a[11], b[11], c[11], cy[11], S_x[11]);
  FA_12 F12(a[12], b[12], c[12], cy[12], S_x[12]);
  FA_13 F13(a[13], b[13], c[13], cy[13], S_x[13]);
  FA_14 F14(a[14], b[14], c[14], cy[14], S_x[14]);
  FA_15 F15(a[15], b[15], c[15], cy[15], S_x[15]);
  FA_16 F16(a[16], b[16], c[16], cy[16], S_x[16]);
  FA_17 F17(a[17], b[17], c[17], cy[17], S_x[17]);
  FA_18 F18(a[18], b[18], c[18], cy[18], S_x[18]);
  FA_19 F19(a[19], b[19], c[19], cy[19], S_x[19]);
  FA_20 F20(a[20], b[20], c[20], cy[20], S_x[20]);
  FA_21 F21(a[21], b[21], c[21], cy[21], S_x[21]);
  FA_22 F22(a[22], b[22], c[22], cy[22], S_x[22]);
  FA_23 F23(a[23], b[23], c[23], cy[23], S_x[23]);
  FA_24 F24(a[24], b[24], c[24], cy[24], S_x[24]);
  FA_25 F25(a[25], b[25], c[25], cy[25], S_x[25]);
  FA_26 F26(a[26], b[26], c[26], cy[26], S_x[26]);
  FA_27 F27(a[27], b[27], c[27], cy[27], S_x[27]);
  FA_28 F28(a[28], b[28], c[28], cy[28], S_x[28]);
  FA_29 F29(a[29], b[29], c[29], cy[29], S_x[29]);
  FA_30 F30(a[30], b[30], c[30], cy[30], S_x[30]);
  FA_31 F31(a[31], b[31], c[31], P[32], S_x[31]);
  grey_cell GR1(G[1], P[1], G[0], Gn[1]);
  grey_cell_1 GR2(G[2], P[2], Gn[1], Gn[2]);
  grey_cell_2 GR3(Gw1[3], Pw1[3], Gn[1], Gn[3]);
  grey_cell_3 GR4(G[4], P[4], Gn[3], Gn[4]);
  grey_cell_4 GR5(Gw2[5], Pw2[5], Gn[1], Gn[5]);
  grey_cell_5 GR6(G[6], P[6], Gn[5], Gn[6]);
  grey_cell_6 GR7(Gw2[7], Pw2[7], Gn[3], Gn[7]);
  grey_cell_7 GR8(G[8], P[8], Gn[7], Gn[8]);
  grey_cell_8 GR9(Gw3[9], Pw3[9], Gn[1], Gw4[9]);
  grey_cell_9 GR10(G[10], P[10], Gw4[9], Gn[10]);
  grey_cell_10 GR11(Gw3[11], Pw3[11], Gn[3], Gw4[11]);
  grey_cell_11 GR12(G[12], P[12], Gw4[11], Gn[12]);
  grey_cell_12 GR13(Gw3[13], Pw3[13], Gn[5], Gw4[13]);
  grey_cell_13 GR14(G[14], P[14], Gw4[13], Gn[14]);
  grey_cell_14 GR15(Gw3[15], Pw3[15], Gn[7], Gw4[15]);
  grey_cell_15 GR16(G[16], P[16], Gw4[15], Gn[16]);
  grey_cell_16 GR17(Gw4[17], Pw4[17], Gn[1], Gw5[17]);
  grey_cell_17 GR18(G[18], P[18], Gw5[17], Gn[18]);
  grey_cell_18 GR19(Gw4[19], Pw4[19], Gn[3], Gw5[19]);
  grey_cell_19 GR20(G[20], P[20], Gw5[19], Gn[20]);
  grey_cell_20 GR21(Gw4[21], Pw4[21], Gn[5], Gw5[21]);
  grey_cell_21 GR22(G[22], P[22], Gw5[21], Gn[22]);
  grey_cell_22 GR23(Gw4[23], Pw4[23], Gn[7], Gw5[23]);
  grey_cell_23 GR24(G[24], P[24], Gw5[23], Gn[24]);
  grey_cell_24 GR25(Gw4[25], Pw4[25], Gw4[9], Gw5[25]);
  grey_cell_25 GR26(G[26], P[26], Gw5[25], Gn[26]);
  grey_cell_26 GR27(Gw4[27], Pw4[27], Gw4[11], Gw5[27]);
  grey_cell_27 GR28(G[28], P[28], Gw5[27], Gn[28]);
  grey_cell_28 GR29(Gw4[29], Pw4[29], Gw4[13], Gw5[29]);
  grey_cell_29 GR30(G[30], P[30], Gw5[29], Gn[30]);
  grey_cell_30 GR31(Gw4[31], Pw4[31], Gw4[15], Gn[31]);
  grey_cell_31 GR32(UNCONNECTED_HIER_Z0, P[32], Gn[31], Cout);
  XOR2M2RA g41(.A (P[1]), .B (G[0]), .Z (S[1]));
  XOR2M2RA g42(.A (Gn[1]), .B (P[2]), .Z (S[2]));
  XOR2M2RA g43(.A (Gn[2]), .B (P[3]), .Z (S[3]));
  XOR2M2RA g44(.A (Gn[3]), .B (P[4]), .Z (S[4]));
  XOR2M2RA g45(.A (Gn[4]), .B (P[5]), .Z (S[5]));
  XOR2M2RA g46(.A (Gn[5]), .B (P[6]), .Z (S[6]));
  XOR2M2RA g47(.A (Gn[6]), .B (P[7]), .Z (S[7]));
  XOR2M2RA g48(.A (Gn[7]), .B (P[8]), .Z (S[8]));
  XOR2M2RA g49(.A (Gn[8]), .B (P[9]), .Z (S[9]));
  XOR2M2RA g50(.A (Gw4[9]), .B (P[10]), .Z (S[10]));
  XOR2M2RA g51(.A (Gn[10]), .B (P[11]), .Z (S[11]));
  XOR2M2RA g52(.A (Gw4[11]), .B (P[12]), .Z (S[12]));
  XOR2M2RA g53(.A (Gn[12]), .B (P[13]), .Z (S[13]));
  XOR2M2RA g54(.A (Gw4[13]), .B (P[14]), .Z (S[14]));
  XOR2M2RA g55(.A (Gn[14]), .B (P[15]), .Z (S[15]));
  XOR2M2RA g56(.A (Gw4[15]), .B (P[16]), .Z (S[16]));
  XOR2M2RA g57(.A (Gn[16]), .B (P[17]), .Z (S[17]));
  XOR2M2RA g58(.A (Gw5[17]), .B (P[18]), .Z (S[18]));
  XOR2M2RA g59(.A (Gn[18]), .B (P[19]), .Z (S[19]));
  XOR2M2RA g60(.A (Gw5[19]), .B (P[20]), .Z (S[20]));
  XOR2M2RA g61(.A (Gn[20]), .B (P[21]), .Z (S[21]));
  XOR2M2RA g62(.A (Gw5[21]), .B (P[22]), .Z (S[22]));
  XOR2M2RA g63(.A (Gn[22]), .B (P[23]), .Z (S[23]));
  XOR2M2RA g64(.A (Gw5[23]), .B (P[24]), .Z (S[24]));
  XOR2M2RA g65(.A (Gn[24]), .B (P[25]), .Z (S[25]));
  XOR2M2RA g66(.A (Gw5[25]), .B (P[26]), .Z (S[26]));
  XOR2M2RA g67(.A (Gn[26]), .B (P[27]), .Z (S[27]));
  XOR2M2RA g68(.A (Gw5[27]), .B (P[28]), .Z (S[28]));
  XOR2M2RA g69(.A (Gn[28]), .B (P[29]), .Z (S[29]));
  XOR2M2RA g70(.A (Gw5[29]), .B (P[30]), .Z (S[30]));
  XOR2M2RA g71(.A (Gn[30]), .B (P[31]), .Z (S[31]));
  XOR2M2RA g72(.A (Gn[31]), .B (P[32]), .Z (S[32]));
endmodule

