
// Generated by Cadence Genus(TM) Synthesis Solution 19.12-s121_1
// Generated on: Nov 11 2021 23:32:44 IST (Nov 11 2021 18:02:44 UTC)

// Verification Directory fv/Adder_16 

module base_logic(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_1(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_2(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_3(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_4(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_5(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_6(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_7(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_8(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_9(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_10(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_11(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_12(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_13(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_14(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module base_logic_15(Si, cyi_1, Pi, Gi);
  input Si, cyi_1;
  output Pi, Gi;
  wire Si, cyi_1;
  wire Pi, Gi;
  ADHM1RA g20(.A (cyi_1), .B (Si), .CO (Gi), .S (Pi));
endmodule

module black_cell(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_1(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_2(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_3(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_4(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_5(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_6(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_7(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_8(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_9(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_10(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_11(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_12(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pik), .B (Pk_1j), .Z (Pij));
endmodule

module black_cell_13(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_14(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_15(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module black_cell_16(Gik, Pik, Gk_1j, Pk_1j, Gij, Pij);
  input Gik, Pik, Gk_1j, Pk_1j;
  output Gij, Pij;
  wire Gik, Pik, Gk_1j, Pk_1j;
  wire Gij, Pij;
  AO21M2RA g21(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
  AN2M2R g22(.A (Pk_1j), .B (Pik), .Z (Pij));
endmodule

module FA(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_1(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_2(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_3(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_4(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_5(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_6(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_7(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_8(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_9(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_10(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_11(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_12(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_13(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_14(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module FA_15(ai, bi, ci, cyi_1, Si);
  input ai, bi, ci;
  output cyi_1, Si;
  wire ai, bi, ci;
  wire cyi_1, Si;
  ADFM2RA g64(.A (bi), .B (ai), .CI (ci), .CO (cyi_1), .S (Si));
endmodule

module grey_cell(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
endmodule

module grey_cell_1(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_2(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_3(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_4(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
endmodule

module grey_cell_5(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_6(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_7(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_8(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
endmodule

module grey_cell_9(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_10(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Pik), .A2 (Gk_1j), .B (Gik), .Z (Gij));
endmodule

module grey_cell_11(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_12(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_13(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_14(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AO21M2RA g14(.A1 (Gk_1j), .A2 (Pik), .B (Gik), .Z (Gij));
endmodule

module grey_cell_15(Gik, Pik, Gk_1j, Gij);
  input Gik, Pik, Gk_1j;
  output Gij;
  wire Gik, Pik, Gk_1j;
  wire Gij;
  AN2M2R g9(.A (Gk_1j), .B (Pik), .Z (Gij));
endmodule

module Adder_16(S, Cout, a, b, c, Cin);
  input [15:0] a, b, c;
  input Cin;
  output [16:0] S;
  output Cout;
  wire [15:0] a, b, c;
  wire Cin;
  wire [16:0] S;
  wire Cout;
  wire [15:0] S_x;
  wire [16:0] G;
  wire [15:0] cy;
  wire [16:0] P;
  wire [16:0] Gw1;
  wire [16:0] Pw1;
  wire [16:0] Gw2;
  wire [16:0] Pw2;
  wire [16:0] Gw3;
  wire [16:0] Pw3;
  wire [16:0] Gn;
  wire [16:0] Gw4;
  wire UNCONNECTED_HIER_Z;
  base_logic B0(S_x[0], Cin, S[0], G[0]);
  base_logic_1 B1(S_x[1], cy[0], P[1], G[1]);
  base_logic_2 B2(S_x[2], cy[1], P[2], G[2]);
  base_logic_3 B3(S_x[3], cy[2], P[3], G[3]);
  base_logic_4 B4(S_x[4], cy[3], P[4], G[4]);
  base_logic_5 B5(S_x[5], cy[4], P[5], G[5]);
  base_logic_6 B6(S_x[6], cy[5], P[6], G[6]);
  base_logic_7 B7(S_x[7], cy[6], P[7], G[7]);
  base_logic_8 B8(S_x[8], cy[7], P[8], G[8]);
  base_logic_9 B9(S_x[9], cy[8], P[9], G[9]);
  base_logic_10 B10(S_x[10], cy[9], P[10], G[10]);
  base_logic_11 B11(S_x[11], cy[10], P[11], G[11]);
  base_logic_12 B12(S_x[12], cy[11], P[12], G[12]);
  base_logic_13 B13(S_x[13], cy[12], P[13], G[13]);
  base_logic_14 B14(S_x[14], cy[13], P[14], G[14]);
  base_logic_15 B15(S_x[15], cy[14], P[15], G[15]);
  black_cell BL3(G[3], P[3], G[2], P[2], Gw1[3], Pw1[3]);
  black_cell_1 BL51(G[5], P[5], G[4], P[4], Gw1[5], Pw1[5]);
  black_cell_2 BL52(Gw1[5], Pw1[5], Gw1[3], Pw1[3], Gw2[5], Pw2[5]);
  black_cell_3 BL71(G[7], P[7], G[6], P[6], Gw1[7], Pw1[7]);
  black_cell_4 BL72(Gw1[7], Pw1[7], Gw1[5], Pw1[5], Gw2[7], Pw2[7]);
  black_cell_5 BL91(G[9], P[9], G[8], P[8], Gw1[9], Pw1[9]);
  black_cell_6 BL92(Gw1[9], Pw1[9], Gw1[7], Pw1[7], Gw2[9], Pw2[9]);
  black_cell_7 BL93(Gw2[9], Pw2[9], Gw2[5], Pw2[5], Gw3[9], Pw3[9]);
  black_cell_8 BL111(G[11], P[11], G[10], P[10], Gw1[11], Pw1[11]);
  black_cell_9 BL112(Gw1[11], Pw1[11], Gw1[9], Pw1[9], Gw2[11],
       Pw2[11]);
  black_cell_10 BL113(Gw2[11], Pw2[11], Gw2[7], Pw2[7], Gw3[11],
       Pw3[11]);
  black_cell_11 BL131(G[13], P[13], G[12], P[12], Gw1[13], Pw1[13]);
  black_cell_12 BL132(Gw1[13], Pw1[13], Gw1[11], Pw1[11], Gw2[13],
       Pw2[13]);
  black_cell_13 BL133(Gw2[13], Pw2[13], Gw2[9], Pw2[9], Gw3[13],
       Pw3[13]);
  black_cell_14 BL151(G[15], P[15], G[14], P[14], Gw1[15], Pw1[15]);
  black_cell_15 BL152(Gw1[15], Pw1[15], Gw1[13], Pw1[13], Gw2[15],
       Pw2[15]);
  black_cell_16 BL153(Gw2[15], Pw2[15], Gw2[11], Pw2[11], Gw3[15],
       Pw3[15]);
  FA F0(a[0], b[0], c[0], cy[0], S_x[0]);
  FA_1 F1(a[1], b[1], c[1], cy[1], S_x[1]);
  FA_2 F2(a[2], b[2], c[2], cy[2], S_x[2]);
  FA_3 F3(a[3], b[3], c[3], cy[3], S_x[3]);
  FA_4 F4(a[4], b[4], c[4], cy[4], S_x[4]);
  FA_5 F5(a[5], b[5], c[5], cy[5], S_x[5]);
  FA_6 F6(a[6], b[6], c[6], cy[6], S_x[6]);
  FA_7 F7(a[7], b[7], c[7], cy[7], S_x[7]);
  FA_8 F8(a[8], b[8], c[8], cy[8], S_x[8]);
  FA_9 F9(a[9], b[9], c[9], cy[9], S_x[9]);
  FA_10 F10(a[10], b[10], c[10], cy[10], S_x[10]);
  FA_11 F11(a[11], b[11], c[11], cy[11], S_x[11]);
  FA_12 F12(a[12], b[12], c[12], cy[12], S_x[12]);
  FA_13 F13(a[13], b[13], c[13], cy[13], S_x[13]);
  FA_14 F14(a[14], b[14], c[14], cy[14], S_x[14]);
  FA_15 F15(a[15], b[15], c[15], P[16], S_x[15]);
  grey_cell GR1(G[1], P[1], G[0], Gn[1]);
  grey_cell_1 GR2(G[2], P[2], Gn[1], Gn[2]);
  grey_cell_2 GR3(Gw1[3], Pw1[3], Gn[1], Gn[3]);
  grey_cell_3 GR4(G[4], P[4], Gn[3], Gn[4]);
  grey_cell_4 GR5(Gw2[5], Pw2[5], Gn[1], Gw3[5]);
  grey_cell_5 GR6(G[6], P[6], Gw3[5], Gn[6]);
  grey_cell_6 GR7(Gw2[7], Pw2[7], Gn[3], Gw3[7]);
  grey_cell_7 GR8(G[8], P[8], Gw3[7], Gn[8]);
  grey_cell_8 GR9(Gw3[9], Pw3[9], Gn[1], Gw4[9]);
  grey_cell_9 GR10(G[10], P[10], Gw4[9], Gn[10]);
  grey_cell_10 GR11(Gw3[11], Pw3[11], Gn[3], Gw4[11]);
  grey_cell_11 GR12(G[12], P[12], Gw4[11], Gn[12]);
  grey_cell_12 GR13(Gw3[13], Pw3[13], Gw3[5], Gw4[13]);
  grey_cell_13 GR14(G[14], P[14], Gw4[13], Gn[14]);
  grey_cell_14 GR15(Gw3[15], Pw3[15], Gw3[7], Gn[15]);
  grey_cell_15 GR16(UNCONNECTED_HIER_Z, P[16], Gn[15], Cout);
  XOR2M2RA g25(.A (P[1]), .B (G[0]), .Z (S[1]));
  XOR2M2RA g26(.A (Gn[1]), .B (P[2]), .Z (S[2]));
  XOR2M2RA g27(.A (Gn[2]), .B (P[3]), .Z (S[3]));
  XOR2M2RA g28(.A (Gn[3]), .B (P[4]), .Z (S[4]));
  XOR2M2RA g29(.A (Gn[4]), .B (P[5]), .Z (S[5]));
  XOR2M2RA g30(.A (Gw3[5]), .B (P[6]), .Z (S[6]));
  XOR2M2RA g31(.A (Gn[6]), .B (P[7]), .Z (S[7]));
  XOR2M2RA g32(.A (Gw3[7]), .B (P[8]), .Z (S[8]));
  XOR2M2RA g33(.A (Gn[8]), .B (P[9]), .Z (S[9]));
  XOR2M2RA g34(.A (Gw4[9]), .B (P[10]), .Z (S[10]));
  XOR2M2RA g35(.A (Gn[10]), .B (P[11]), .Z (S[11]));
  XOR2M2RA g36(.A (Gw4[11]), .B (P[12]), .Z (S[12]));
  XOR2M2RA g37(.A (Gn[12]), .B (P[13]), .Z (S[13]));
  XOR2M2RA g38(.A (Gw4[13]), .B (P[14]), .Z (S[14]));
  XOR2M2RA g39(.A (Gn[14]), .B (P[15]), .Z (S[15]));
  XOR2M2RA g40(.A (Gn[15]), .B (P[16]), .Z (S[16]));
endmodule

